import type { SceneKind, Topic, TopicFamily } from './types.ts'

export interface ConceptSeed {
  title: string
  focus: string
}

const parse = (rows: string[]): ConceptSeed[] => rows.map((row) => {
  const [title, focus] = row.split('|')
  return { title, focus }
})

export const conceptGroups: Record<Topic, ConceptSeed[]> = {
  javascript: parse([
    'var, let, and const|let and const are block scoped, var is function scoped, and const prevents rebinding rather than deep mutation.',
    'Primitive and reference values|Primitives are copied by value while objects are referenced through values that point to shared objects.',
    'Implicit type coercion|JavaScript converts values according to operation-specific rules, so explicit conversion is clearer at boundaries.',
    'Loose and strict equality|Strict equality avoids coercion while loose equality follows a complex conversion algorithm before comparison.',
    'Truthy and falsy values|Conditionals coerce values to boolean; only false, zero, empty string, null, undefined, and NaN are falsy.',
    'Lexical scope|A function resolves identifiers from where it was defined, moving outward through nested lexical environments.',
    'Hoisting|Declarations are registered before execution, but initialization behavior differs for functions, var, let, and const.',
    'Temporal dead zone|A let or const binding exists from block entry but cannot be accessed before its declaration is evaluated.',
    'Closures|A function retains access to the lexical environment in which it was created even after that outer function returns.',
    'The this value|For regular functions, this depends on the call site rather than where the function was written.',
    'Arrow function this|Arrow functions capture this lexically and cannot be rebound with call, apply, or bind.',
    'call, apply, and bind|call and apply invoke immediately with an explicit this value, while bind creates a new bound function.',
    'Prototype chain|Property lookup walks from an object to its prototype repeatedly until a match is found or the chain ends.',
    'JavaScript classes|Class syntax is a clearer layer over prototype-based construction, methods, inheritance, and super calls.',
    'Prototype inheritance|Objects can delegate missing property lookup to another object, enabling shared behavior without copying methods.',
    'The event loop|The runtime executes one call stack while queues schedule callbacks when the stack becomes empty.',
    'The call stack|Each function call adds a frame containing local execution state and returns by removing that frame.',
    'Tasks and microtasks|Promise reactions use the microtask queue, which drains before the next timer or other task runs.',
    'Promises|A promise represents a future settled value and chains transformations while forwarding fulfillment or rejection.',
    'async and await|An async function returns a promise, and await pauses that function while allowing the event loop to continue.',
    'Promise combinators|all, allSettled, race, and any express different coordination and failure rules for concurrent promises.',
    'Error propagation|Thrown errors travel up the active call chain until caught, otherwise they terminate that execution path.',
    'try, catch, and finally|catch handles a thrown error while finally runs cleanup regardless of success or failure.',
    'Higher-order functions|Functions can receive or return functions, enabling reusable behaviors such as mapping and composition.',
    'Pure functions|A pure function has no observable side effects and returns the same result for the same inputs.',
    'Mutation and immutability|Mutation changes an existing value, while immutable updates create new structures that make changes easier to track.',
    'Array transformation methods|map transforms, filter selects, find returns one match, and some or every test conditions.',
    'map versus forEach|map creates a new array from returned values, while forEach is intended for side effects and returns undefined.',
    'Reducing arrays|reduce folds a sequence into one accumulated result using an explicit initial value and reducer.',
    'Destructuring|Destructuring extracts object properties or array positions into bindings with defaults and renaming.',
    'Spread and rest syntax|Spread expands an iterable or object, while rest collects remaining values into one binding.',
    'Optional chaining and nullish coalescing|Optional chaining stops on nullish values and ?? falls back only for null or undefined.',
    'ECMAScript modules|ES modules use static import and export declarations that enable analysis, live bindings, and tree shaking.',
    'CommonJS versus ES modules|CommonJS loads with require at runtime while ES modules use static declarations and live bindings.',
    'JSON serialization|JSON supports a limited data model and loses functions, undefined, symbols, prototypes, and some numeric values.',
    'Shallow and deep copies|A shallow copy duplicates only the outer container, so nested object references remain shared.',
    'Object equality|Objects compare by reference identity, not by recursively comparing their properties.',
    'Map and Set|Map stores arbitrary key-value pairs and Set stores unique values with predictable lookup semantics.',
    'WeakMap and WeakSet|Weak collections hold object keys without preventing garbage collection and are not enumerable.',
    'Iterators and generators|Iterators produce a sequence through next, while generator functions build iterators with yield.',
    'Symbols|A Symbol is a unique primitive often used for collision-resistant property keys and language protocols.',
    'Property descriptors|Descriptors control whether a property is writable, enumerable, configurable, or implemented with accessors.',
    'Debouncing and throttling|Debounce waits for quiet time while throttle limits how often work can run during repeated events.',
    'Memoization|Memoization caches output by input and is safe only when cache keys and invalidation match the function behavior.',
    'Recursion|A recursive function solves a problem through smaller calls and requires a reachable base case.',
    'Currying|Currying transforms a multi-argument function into a sequence of single-argument functions.',
    'Function declarations and expressions|Declarations are initialized during environment setup, while expressions are created when execution reaches them.',
    'Default parameters|Defaults run when an argument is undefined and can reference earlier parameters.',
    'Template literals|Template literals support interpolation, multiline strings, and tagged processing without manual concatenation.',
    'Regular expressions|Regular expressions describe text patterns, but readable parsing logic is preferable for complex grammars.',
    'Dates and time zones|A Date represents an instant while display and calendar calculations depend on an explicit time zone.',
    'Floating-point arithmetic|Most JavaScript numbers use IEEE 754 binary floating point, so some decimal fractions are approximate.',
    'BigInt|BigInt represents integers beyond Number safe precision but cannot be mixed directly with Number arithmetic.',
    'Garbage collection and leaks|Garbage collection reclaims unreachable objects; leaks occur when unintended references keep data reachable.',
    'Browser storage and cookies|Cookies travel with HTTP requests, localStorage is synchronous, and IndexedDB stores larger structured data.'
  ]),
  react: parse([
    'Components|Components are reusable render functions whose output is determined by props, state, and context.',
    'Props|Props are read-only inputs passed from a parent and should not be mutated by the receiving component.',
    'State|State is component memory whose setter schedules a render with a new snapshot.',
    'The render phase|Rendering calculates the next UI and must stay pure because React may run it more than once.',
    'Reconciliation|React compares element trees and preserves or replaces component state based on type, position, and key.',
    'List keys|A stable key identifies an item among siblings so React can preserve the correct state across changes.',
    'React events|Event handlers respond to user actions and are the right place for side effects caused by those actions.',
    'Controlled inputs|A controlled input receives its value from React state and reports changes through an event handler.',
    'Uncontrolled inputs|An uncontrolled input keeps its current value in the DOM and is accessed through a ref or form data.',
    'Lifting state up|Shared state belongs in the closest common ancestor that coordinates the components using it.',
    'Component composition|Composition combines focused components through props and children instead of deep inheritance.',
    'Context|Context supplies data to a subtree without repetitive props, but broad changing context can trigger many renders.',
    'useState|useState stores a snapshot and accepts functional updates when the next value depends on the previous one.',
    'State batching|React groups state updates in an event before rendering, so multiple setters do not immediately change variables.',
    'useReducer|useReducer centralizes state transitions in a pure reducer and suits related or complex updates.',
    'Purpose of effects|Effects synchronize a component with an external system after React commits the UI.',
    'Effect dependencies|Every reactive value read by an effect belongs in its dependency list unless the code is restructured.',
    'Effect cleanup|Cleanup stops subscriptions, timers, requests, or connections before rerun and unmount.',
    'useMemo|useMemo caches a calculated value as a performance optimization, not as a correctness guarantee.',
    'useCallback|useCallback caches a function reference when referential stability helps a memoized consumer.',
    'React.memo|React.memo can skip rendering when props are shallowly equal, but comparison also has a cost.',
    'Refs|A ref stores a mutable value without causing renders and can point to a DOM node for imperative operations.',
    'Custom hooks|A custom hook packages reusable stateful logic while each caller keeps independent state.',
    'Rules of Hooks|Hooks run at the top level in the same order so React can associate calls with stored state.',
    'Conditional rendering|JavaScript conditions choose which elements to return; state preservation still follows tree position and keys.',
    'Rendering lists|Lists are produced with array transforms and stable data-derived keys, not array positions when order changes.',
    'React forms|Forms combine semantic HTML, validation, submission handling, and controlled or uncontrolled field strategies.',
    'Error boundaries|An error boundary catches rendering errors in descendants and renders fallback UI, but not event-handler errors.',
    'Suspense|Suspense coordinates a fallback while a compatible child is waiting for code or data.',
    'Lazy loading|React.lazy defers loading a component module and is paired with a Suspense fallback.',
    'Portals|A portal renders children elsewhere in the DOM while preserving their place in the React tree and event flow.',
    'Strict Mode|Strict Mode adds development-only checks and repeats selected behavior to expose unsafe side effects.',
    'Hydration|Hydration attaches React behavior to server-rendered HTML and requires compatible initial output.',
    'React performance profiling|The Profiler and browser tools identify measured render costs before memoization is added.',
    'Accessible React interfaces|React does not replace semantic HTML, labels, focus order, keyboard support, or accessible names.'
  ]),
  nextjs: parse([
    'The App Router|The App Router uses filesystem segments, nested layouts, and React Server Components for route composition.',
    'Pages and layouts|A page defines route content while a layout wraps segments and preserves shared UI across navigation.',
    'Server and Client Components|Server Components run on the server by default; Client Components add state, events, and browser APIs.',
    'The use client boundary|The directive marks a client module boundary, and its imports become part of the client graph.',
    'React Server Component payload|The server sends a compact component representation that React uses with HTML to reconcile the UI.',
    'App Router data fetching|Server Components can fetch data directly near the component that needs it without a client effect.',
    'Next.js caching|Caching behavior depends on the API and route configuration, so freshness must be chosen explicitly.',
    'Static and dynamic rendering|Static output is reusable across requests while dynamic rendering uses request-time information.',
    'Route Handlers|A route.ts file handles HTTP methods with Web Request and Response APIs inside the app directory.',
    'Server Actions|A server action executes trusted server code from a form or transition and must validate authorization and input.',
    'Loading, error, and not-found files|Special route files define streaming fallbacks, error recovery, and missing-resource UI.',
    'Metadata|Static or generated metadata supplies titles, descriptions, and social information for route segments.',
    'Request middleware|Middleware runs before a matched response and is useful for lightweight redirects, headers, and access routing.',
    'Streaming with Suspense|Suspense boundaries let ready route content stream while slower regions show meaningful fallbacks.',
    'Image and font optimization|Built-in components reserve layout space and optimize delivery, while local fonts avoid external runtime requests.'
  ]),
  backend: parse([
    'HTTP methods|HTTP methods express request semantics such as retrieval, creation, replacement, partial update, and deletion.',
    'HTTP status codes|Status codes communicate result categories and should distinguish success, client errors, and server failures accurately.',
    'HTTP headers|Headers carry representation, authentication, caching, negotiation, and tracing metadata around a message body.',
    'Request and response lifecycle|A server parses a request, runs middleware and handlers, performs I/O, and constructs one response.',
    'REST constraints|REST emphasizes resources, uniform interfaces, stateless requests, cacheability, and layered components.',
    'Resource-oriented URLs|URLs identify nouns while methods express actions, keeping the interface predictable.',
    'Idempotency|An idempotent operation can be repeated with the same intended effect, which matters during retries.',
    'Pagination|Cursor pagination remains stable for changing datasets, while offset pagination is simpler but can shift and slow down.',
    'Filtering and sorting|APIs validate an allowlist of filter and sort fields before safely translating them into queries.',
    'API versioning|Versioning protects existing consumers when an API must make incompatible contract changes.',
    'Input validation|Treat every external value as untrusted and validate shape, type, range, and business rules at the boundary.',
    'API error design|Errors need stable machine codes, safe messages, appropriate status, and a trace identifier without leaking internals.',
    'Express middleware|Middleware forms an ordered request pipeline and must either finish the response or call next.',
    'Authentication and authorization|Authentication establishes identity; authorization decides whether that identity may perform an action.',
    'Sessions and JWTs|Server sessions centralize revocation while JWTs carry signed claims and still require expiry and authorization checks.',
    'Secure cookies|HttpOnly, Secure, and SameSite attributes reduce script access, transport exposure, and cross-site request risk.',
    'CORS|CORS is a browser policy that controls which origins may read cross-origin responses; it is not authentication.',
    'CSRF|CSRF abuses automatically attached credentials, so defenses include SameSite cookies, tokens, and origin validation.',
    'Cross-site scripting|XSS executes attacker-controlled content in a page and is reduced through output encoding and strict content policies.',
    'SQL injection|Parameterized queries keep data separate from SQL syntax and prevent input from changing the command structure.',
    'Rate limiting|Rate limits bound repeated work by an appropriate identity and return clear retry information.',
    'Password hashing|Passwords require slow salted password hashing such as Argon2 or bcrypt, never reversible encryption.',
    'Environment secrets|Secrets stay outside source control, use least privilege, rotate safely, and never enter browser bundles.',
    'Structured logging|Structured logs capture consistent fields and correlation IDs while excluding secrets and unnecessary personal data.',
    'API testing|Tests cover contracts, authorization, validation, persistence boundaries, and failure behavior, not only happy paths.',
    'Node.js event loop|Node coordinates nonblocking I/O through an event loop while CPU-heavy JavaScript still blocks its main thread.',
    'Node.js streams|Streams process data in chunks with backpressure instead of buffering an entire payload in memory.',
    'Express routing|Routers group route paths and middleware while handler order determines which code runs.',
    'Express error middleware|Error middleware uses four parameters, centralizes safe responses, and runs after next receives an error.',
    'Relational data modeling|Relational schemas represent entities, relationships, constraints, and queries explicitly.',
    'Primary keys|A primary key uniquely and stably identifies a row and supports references from other tables.',
    'Foreign keys|A foreign key enforces that a referenced relationship points to an existing permitted row.',
    'Database normalization|Normalization reduces update anomalies by separating facts according to their dependencies.',
    'SQL joins|Joins combine related rows according to a predicate, with inner and outer joins differing on unmatched rows.',
    'Database indexes|An index speeds selected reads by maintaining an additional ordered structure at write and storage cost.',
    'Transactions|A transaction groups operations into one success or failure boundary and must be kept as short as practical.',
    'ACID properties|Atomicity, consistency, isolation, and durability describe core transaction guarantees.',
    'Isolation levels|Isolation levels trade concurrency for protection against anomalies such as nonrepeatable reads and phantoms.',
    'Database constraints|NOT NULL, UNIQUE, CHECK, primary keys, and foreign keys enforce invariants close to the data.',
    'Connection pooling and N+1 queries|Pools reuse limited database connections, while batching or joins prevent one query per parent row.'
  ]),
  fullstack: parse([
    'End-to-end request lifecycle|A user action crosses browser state, network, server logic, database work, and response rendering.',
    'CSR, SSR, and SSG|Client, request-time server, and build-time rendering trade freshness, infrastructure, interactivity, and initial delivery.',
    'Hydration boundaries|Server HTML becomes interactive when client code hydrates matching regions, so initial output must agree.',
    'Client and server state|Client state describes local interaction while server state is remote data with caching and synchronization concerns.',
    'API contracts|A contract defines request and response shapes, validation, errors, and compatibility between independently changing layers.',
    'Data transfer objects|A DTO exposes an intentional transport shape instead of leaking database rows or internal objects.',
    'Optimistic interfaces|Optimistic updates show the expected result immediately and must reconcile success, rollback, and concurrent changes.',
    'Caching layers|Browser, CDN, application, and database caches need explicit keys, freshness, invalidation, and ownership boundaries.',
    'Content delivery networks|A CDN serves cacheable content near users and forwards misses to the origin.',
    'Cookie and token flows|Credential transport, storage, expiry, rotation, and CSRF exposure depend on where tokens are kept.',
    'Full-stack authentication flow|A secure flow verifies identity, establishes a session, and rechecks authorization for every protected operation.',
    'Role and ownership access|Permissions need both role checks and resource ownership rules rather than relying on hidden controls.',
    'Validation across layers|The client improves feedback, the server enforces trust boundaries, and the database enforces durable invariants.',
    'Cross-layer error handling|Errors should be logged with private context while users receive stable, actionable, safe messages.',
    'Loading and empty states|Loading explains pending work, empty states direct the next action, and errors provide recovery.',
    'Web performance|Performance work targets measured bottlenecks in delivery, rendering, JavaScript execution, images, and data access.',
    'Core Web Vitals|LCP measures loading, INP responsiveness, and CLS visual stability from the user experience.',
    'Web accessibility|Semantic structure, keyboard operation, focus, contrast, labels, and announcements are full-stack quality requirements.',
    'Responsive design|Responsive interfaces adapt content priority and layout to available space rather than targeting named devices.',
    'Search engine optimization|Useful metadata, crawlable content, semantic markup, performance, and stable URLs support discovery.',
    'Deployment pipeline|A deployment builds an immutable artifact, applies configuration, migrates safely, verifies health, and supports rollback.',
    'Environment separation|Development, preview, and production isolate configuration and data while promoting the same artifact.',
    'Continuous integration and delivery|CI verifies each change and CD promotes validated artifacts through controlled environments.',
    'Containers|A container packages a process and dependencies, while orchestration and persistent data remain separate concerns.',
    'Reverse proxies|A reverse proxy terminates connections and routes traffic to internal services while applying shared policies.',
    'DNS|DNS maps names to records through cached hierarchical resolution before an HTTP connection begins.',
    'HTTPS and TLS|TLS authenticates the server and protects transport confidentiality and integrity, but not application authorization.',
    'WebSockets|WebSockets provide a long-lived two-way channel and require connection authorization, heartbeats, and scaling strategy.',
    'Polling and server-sent events|Polling repeatedly requests updates while SSE streams one-way server events over HTTP.',
    'Background jobs and queues|Queues separate slow or retryable work from request latency and require idempotent consumers.',
    'Secure file uploads|Uploads need size and type validation, generated names, isolated storage, and safe delivery headers.',
    'Observability|Logs, metrics, and traces connect user-visible failures to behavior across services.',
    'Feature flags|Flags separate deployment from release and require ownership, safe defaults, and eventual cleanup.',
    'Monorepos|A monorepo coordinates related packages and tooling but needs clear boundaries, dependency rules, and selective builds.',
    'Defense in depth|Multiple independent controls reduce the chance that one validation or authorization mistake becomes a breach.'
  ]),
  git: parse([
    'Working tree, index, and repository|Git separates edited files, the staged snapshot, and committed history into distinct states.',
    'Adding and committing|git add selects content for the index and git commit records that staged snapshot with its parent.',
    'Status and diff|status summarizes states while diff compares working, staged, committed, or branch snapshots.',
    'Branches and switch|A branch is a movable commit reference, and switching updates HEAD plus the working tree.',
    'Merging branches|A merge combines histories and may create a merge commit when fast-forwarding is not possible.',
    'Resolving conflicts|Conflicts mark competing changes for a human to reconcile before staging the resolved result.',
    'Rebasing|Rebase replays commits onto a new base and rewrites commit identities, so shared history needs care.',
    'Merge versus rebase|Merge preserves branch topology while rebase creates a linear rewritten sequence.',
    'Reset modes|Soft, mixed, and hard reset move HEAD while differing in how they update the index and working tree.',
    'Revert|Revert adds a new commit that inverses an earlier change, making it safe for shared history.',
    'Restore|Restore copies file content from an index or commit without moving branch history.',
    'Stashing|Stash records selected uncommitted work temporarily so another working state can be checked out.',
    'Cherry-pick|Cherry-pick applies the change introduced by selected commits onto the current branch as new commits.',
    'Tags|A tag names a specific object, commonly marking a release, and annotated tags carry metadata.',
    'Remotes|A remote is a named repository URL with remote-tracking references for observed branch state.',
    'Fetch and pull|Fetch updates remote-tracking data; pull fetches and then integrates into the current branch.',
    'Push and upstream branches|Push transfers reachable objects and updates a remote ref subject to fast-forward and permission rules.',
    'gitignore|Ignore rules prevent untracked paths from appearing, but do not remove files already tracked.',
    'Pull requests and review|A pull request proposes branch integration and provides a place for checks, discussion, and review.',
    'GitHub Actions|Actions run repository workflows from events using jobs, steps, permissions, secrets, and isolated runners.'
  ])
}

export const topicMeta: Record<Topic, { family: TopicFamily; label: string; reference: string; scene: SceneKind }> = {
  javascript: { family: 'javascript', label: 'JavaScript', reference: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', scene: 'execution' },
  react: { family: 'frontend', label: 'React', reference: 'https://react.dev/learn', scene: 'component-tree' },
  nextjs: { family: 'frontend', label: 'Next.js', reference: 'https://nextjs.org/docs/app', scene: 'request-flow' },
  backend: { family: 'backend', label: 'APIs and databases', reference: 'https://developer.mozilla.org/en-US/docs/Web/HTTP', scene: 'database' },
  fullstack: { family: 'fullstack', label: 'Full-stack', reference: 'https://developer.mozilla.org/en-US/docs/Learn_web_development', scene: 'request-flow' },
  git: { family: 'git', label: 'Git and GitHub', reference: 'https://git-scm.com/docs', scene: 'git-graph' }
}
